FuelPrice/fuelprice/prices/urls.py
# from django.urls import path
# from fuelprice.prices import views
#
# app_name = 'prices'
#
# urlpatterns = [
#     path('', views.PriceListView.as_view(), name='price-list'),
#     path('add/', views.PriceCreateView.as_view(), name='price-create'),
# ]

from django.urls import path
from . import views

app_name = 'prices'

urlpatterns = [
    path('', views.PriceListView.as_view(), name='price-list'),
    path('add/', views.PriceCreateView.as_view(), name='price-create'),
]

FuelPrice/fuelprice/stations/urls.py
from django.urls import path
from . import views

app_name = 'stations'

urlpatterns = [
    path('', views.StationListView.as_view(), name='station-list'),
    path('add/', views.StationCreateView.as_view(), name='station-create'),
]

FuelPrice/fuelprice/urls.py
# FuelPrice/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stations/', include('fuelprice.stations.urls', namespace='stations')),
    path('prices/', include('fuelprice.prices.urls', namespace='prices')),
]

FuelPrice/fuelprice/prices/models.py
from django.db import models

class Station(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)

class FuelPrice(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    fuel_type = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)

FuelPrice/fuelprice/stations/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

class Station(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

FuelPrice/fuelprice/prices/forms.py
from django import forms
from .models import FuelPrice

class FuelPriceForm(forms.ModelForm):
    class Meta:
        model = FuelPrice
        fields = ['station', 'fuel_type', 'price']

FuelPrice/fuelprice/stations/forms.py
from django import forms
from .models import Station

class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['name', 'address', 'city']

FuelPrice/fuelprice/prices/views.py
from django.views.generic import ListView, CreateView
from .models import FuelPrice
from .forms import FuelPriceForm

class PriceListView(ListView):
    model = FuelPrice
    template_name = 'prices/price_list.html'
    context_object_name = 'prices'

class PriceCreateView(CreateView):
    model = FuelPrice
    form_class = FuelPriceForm
    template_name = 'prices/price_create.html'
    success_url = '/prices/'

FuelPrice/fuelprice/stations/views.py
from django.views.generic import ListView, CreateView
from .models import Station
from .forms import StationForm

class StationListView(ListView):
    model = Station
    template_name = 'stations/station_list.html'
    context_object_name = 'stations'

class StationCreateView(CreateView):
    model = Station
    form_class = StationForm
    template_name = 'stations/station_create.html'
    success_url = '/stations/'

FuelPrice/fuelprice/templates/stations/station_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Dodaj stację</title>
</head>
<body>
    <h1>Dodaj stację</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Dodaj</button>
    </form>
    <a href="{% url 'stations:station-list' %}">Powrót do listy stacji</a>
</body>
</html>

FuelPrice/fuelprice/templates/stations/station_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista stacji</title>
</head>
<body>
    <h1>Lista stacji</h1>
    <ul>
        {% for station in stations %}
            <li>{{ station.name }} - {{ station.address }} ({{ station.city.name }})</li>
        {% empty %}
            <li>Brak stacji</li>
        {% endfor %}
    </ul>
    <a href="{% url 'stations:station-create' %}">Dodaj stację</a>
</body>
</html>